#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-hoe-git
Version  : 1.6.0
Release  : 9
URL      : https://rubygems.org/downloads/hoe-git-1.6.0.gem
Source0  : https://rubygems.org/downloads/hoe-git-1.6.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-hoe
BuildRequires : rubygem-minitest
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-test-unit

%description
= Hoe Loves Git
* http://github.com/jbarnette/hoe-git
* http://docs.seattlerb.org/hoe-git

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n hoe-git-1.6.0
gem spec %{SOURCE0} -l --ruby > rubygem-hoe-git.gemspec

%build
gem build rubygem-hoe-git.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
hoe-git-1.6.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/hoe-git-1.6.0
rake --trace test TESTOPTS="-v"
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/hoe-git-1.6.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/hoe-git-1.6.0/.autotest
/usr/lib64/ruby/gems/2.3.0/gems/hoe-git-1.6.0/CHANGELOG.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/hoe-git-1.6.0/Manifest.txt
/usr/lib64/ruby/gems/2.3.0/gems/hoe-git-1.6.0/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/hoe-git-1.6.0/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/hoe-git-1.6.0/lib/hoe/git.rb
/usr/lib64/ruby/gems/2.3.0/specifications/hoe-git-1.6.0.gemspec
